GET http://localhost:8080/foo HTTP/1.1
content-type: application/json
Authorization: Bearer ...

###

GET http://localhost:8080/me HTTP/1.1
content-type: application/json
Authorization: Bearer ...


###
# - validates audience
# - validates expiration
# - automatically promotes roles from within the token
