GET https://xstof-java-spring-api.azurewebsites.net/api/greeting
content-type: application/json

###

GET http://localhost:8080/api/greeting HTTP/1.1
content-type: application/json

###


GET http://localhost:8080/api/me HTTP/1.1
content-type: application/json
Authorization: Bearer ...

###

GET http://localhost:8080/api/foo HTTP/1.1
content-type: application/json
Authorization: Bearer ...
#Authorization: {{$aadV2Token 3fd11e85-d8ce-4c7f-b6a0-816346615777}}

###

POST http://localhost:8080/api/foo HTTP/1.1
content-type: application/json
Authorization: Bearer ...

{}

# validations:
# - works: validates issuer
# - works: validates 'write' scope when doing: .antMatchers(HttpMethod.GET, "/foo").hasAnyAuthority("SCOPE_write")
# - works: validate token expiration and validate token not before
# - works: validates role => once configure to support roles
# - works: validates audience => once configured to support audience validation (which is not by default)

# resources:
# - https://docs.spring.io/spring-security/site/docs/5.4.1/reference/html5/#oauth2resourceserver-jwt-authorization-extraction
